# High-tier verdicts. rank -> (verdict, molecules, method, data_status, notes)
#   verdict: "K" keep | "D:<reason>" drop
#   data_status "pending" = needs the browser SI sweep to confirm links
D = {
 1:  ("D:derived_use", "", "", "", "photodissociation cross-sections; reuses SO MARVEL of 23BrYuTe"),
 2:  ("K", "CO", "marvel", "pending", "5 minor CO isotopologues; ApJS SI"),
 3:  ("K", "KH", "exomol_linelist", "pending", "empirical X/A/B levels; MNRAS SI"),
 4:  ("D:linelist_only", "", "", "", "CoYuTe 14NH2D/14ND2H line lists; no own empirical set"),
 5:  ("K", "BH", "exomol_linelist", "pending", "6 BH isotopologues; IOP PPCF SI"),
 6:  ("D:measurement_source", "", "", "", "assigned room-T H2O line list; a MARVEL source, not a run"),
 7:  ("D:ab_initio", "", "", "", "first-principles OH B-X/D-X study"),
 8:  ("K", "CO2", "marvel", "levels+trans", "17O13C18O + 17O13C17O"),
 9:  ("K", "CO2", "marvel", "levels+trans", "626M24; OSF repo 10.17605/OSF.IO/9PZEW; 626M24_transitions.txt"),
 10: ("K", "FeH", "marvel", "levels+trans", "term energy analysis; preprint: 10.2139/ssrn.5348719"),
 11: ("D:preprint_dup", "", "", "", "SSRN preprint of rank 10"),
 12: ("D:pes_linelist", "", "", "", "OCS PES/DMS + IR line lists"),
 13: ("K", "CO", "marvel", "pending", "12C16O; ApJS SI"),
 14: ("K", "CO2", "marvel", "pending", "16O13C17O + 17O12C17O; Molecular Physics SI"),
 15: ("K", "H2O", "marvel", "pending", "HD17O + HD18O; JPCRD (AIP) SI"),
 16: ("K", "CO2", "marvel", "levels+trans", "16O12C17O"),
 17: ("K", "CS2", "marvel", "levels+trans", "2 isotopologues; preprint: 10.2139/ssrn.5035277"),
 18: ("K", "NH3", "marvel", "levels+trans", "14NH3 update"),
 19: ("D:non_marvel_method", "", "", "", "Ritz-principle evaluation of 16OD"),
 20: ("K", "O3", "marvel", "levels+trans", "16O3; preprint: 10.2139/ssrn.4882917"),
 21: ("D:aggregator", "", "", "", "ExoMolHR database paper"),
 22: ("K", "CO2", "marvel", "pending", "16O12C18O; Wiley JCC SI"),
 23: ("K", "CO2", "marvel", "levels+trans", "18O12C18O, 17O12C18O, 18O13C18O; preprint: 10.2139/ssrn.4863850"),
 24: ("K", "CO2", "marvel", "pending", "16O13C18O; Wiley JCC SI"),
 25: ("D:preprint_dup", "", "", "", "SSRN preprint of rank 23"),
 26: ("K", "H2O", "marvel", "levels+trans", "W2024 H216O; OSF repo 10.17605/OSF.IO/4E237 (W2024.zip); mirror respecth.elte.hu"),
 27: ("K", "CO2", "marvel", "pending", "13C16O2; Wiley JCC SI"),
 28: ("K", "CH4", "marvel", "levels+trans", "empirical rovibrational levels for methane"),
 29: ("D:linelist_only", "", "", "", "C3 variational line list; MARVEL in companion jt915 (rank 52)"),
 30: ("K", "MgO|TiO|VO", "exomol_linelist", "pending", "hybrid line lists; SI carries this work's MARVEL levels; RASTI SI"),
 31: ("D:linelist_only", "", "", "", "OCS OYT8 line list; MARVEL in companion jt916 (rank 53)"),
 32: ("K", "NH", "exomol_linelist", "pending", "trihybrid NH model; MNRAS SI"),
 33: ("K", "PN", "exomol_linelist", "pending", "PaiN; MARVEL analysis of X/A states; MNRAS SI"),
 34: ("K", "H2O", "marvel", "levels+trans", "HD17O theory+experiment"),
 35: ("D:non_marvel_method", "", "", "", "RITZ set of 16O3 levels"),
 36: ("D:aggregator", "", "", "", "ExoMol 2024 database release"),
 37: ("D:preprint_dup", "", "", "", "SSRN preprint of rank 36"),
 38: ("D:preprint_dup", "", "", "", "SSRN preprint of rank 17"),
 39: ("K", "N2O", "marvel", "levels+trans", "14N2 16O empirical rovibrational levels"),
 40: ("D:preprint_dup", "", "", "", "SSRN preprint of rank 20"),
 41: ("D:linelist_only", "", "", "", "CH4 MM line list; MARVEL in companion 24KeBoYu (rank 28)"),
 42: ("D:linelist_only", "", "", "", "N2O TYM line list; MARVEL in companion (rank 39)"),
 43: ("K", "NH3", "exomol_linelist", "pending", "15NH3; SI states MARVEL input(+segment) and output energy files; MNRAS SI"),
 44: ("D:linelist_only", "", "", "", "H3+/H2D+/D2H+/D3+ line lists; MARVEL in companions ranks 124-125"),
 45: ("K", "SO", "exomol_linelist", "pending", "SOLIS; SI item (b) is the MARVEL data set; MNRAS SI"),
 46: ("K", "C2H2", "marvel", "pending", "kHz absolute frequencies + improved SN; RSC PCCP SI"),
 47: ("K", "H2CO", "marvel", "levels+trans", "comb-FTS line list + improved MARVEL"),
 48: ("D:linelist_only", "", "", "", "H2CS MOTY line list; MARVEL in companion (rank 59)"),
 49: ("D:linelist_only", "", "", "", "LiOH line lists; no empirical set"),
 50: ("D:linelist_only", "", "", "", "CH+ line lists; no MARVEL analysis"),
 51: ("D:linelist_only", "", "", "", "ZrO ZorrO model; MARVEL in companion 18McBoGo (rank 96)"),
 52: ("K", "C3", "marvel", "pending", "empirical rovibronic levels of C3; Molecular Physics SI"),
 53: ("K", "OCS", "marvel", "pending", "SI = MARVEL input transitions + output energies + segment file; Molecular Physics SI"),
 54: ("K", "AlH", "exomol_linelist", "pending", "AloHa AlH+AlD; MNRAS SI"),
 55: ("K", "YO", "exomol_linelist", "pending", "BRYTS; MNRAS SI; preprint: 10.48550/arxiv.2308.04173"),
 56: ("D:preprint_dup", "", "", "", "arXiv preprint of rank 55"),
 57: ("K", "VO", "marvel", "pending", "fine/hyperfine resolved empirical VO levels; Elsevier SI not exposed by asset probe"),
 58: ("K", "CH|OH", "marvel", "pending", "12CH and 16OH doublet rovibronic; RSC PCCP SI"),
 59: ("K", "H2CS", "marvel", "levels+trans", "MARVEL analysis of H2CS"),
 60: ("K", "CaH|MgH", "exomol_linelist", "pending", "XAB; new CaH/MgH data sets; MNRAS SI"),
 61: ("D:linelist_only", "", "", "", "CaOH OYT6; MARVEL in companion 20YiOwTe (rank 86)"),
 62: ("K", "VO", "marvel", "levels+trans", "empirical model, 11 electronic states"),
 63: ("K", "SiN", "exomol_linelist", "pending", "SiNful; SI = MARVEL input transitions + output energies; MNRAS SI"),
 64: ("K", "AlCl", "exomol_linelist", "pending", "Al35Cl/Al37Cl empirical model; MNRAS SI"),
 65: ("K", "H2CO", "marvel", "levels+trans", "xMARVEL input/output files in SI"),
 66: ("K", "AlO", "exomol_linelist", "pending", "27Al16O MARVEL: 22473 transitions, 6485 levels; MNRAS SI"),
 67: ("K", "NO", "marvel", "pending", "A/B/C states empirical levels; AIP JCP SI (3 text files)"),
 68: ("D:no_doi_dup", "", "", "", "duplicate of rank 67, no DOI"),
 69: ("D:linelist_only", "", "", "", "NO XABC line list; empirical levels in companion (rank 67)"),
 70: ("K", "HOCl", "marvel", "levels+trans", "H16O35Cl"),
 71: ("K", "CN", "exomol_linelist", "pending", "Trihybrid CN; updated MARVEL files in SI; MNRAS SI"),
 72: ("D:aggregator", "", "", "", "ExoMol at 10 review"),
 73: ("K", "SiO", "exomol_linelist", "pending", "SiOUVenIR; SI = MARVEL input transitions + output energy levels; MNRAS SI"),
 74: ("D:linelist_only", "", "", "", "acetylene aCeTY; MARVEL in companion 17ChJoFr (rank 103)"),
 75: ("D:pes_linelist", "", "", "", "H2O semi-empirical PES; supplement is PES Fortran code"),
 76: ("D:preprint_dup", "", "", "", "ACPD preprint of rank 75"),
 77: ("K", "H2O", "marvel", "pending", "W2020 H216O; JPCRD (AIP) SI"),
 78: ("K", "H2O", "marvel", "pending", "W2020 II: H217O + H218O; JPCRD (AIP) SI"),
 79: ("K", "NH3", "marvel", "levels+trans", "14NH3 up to 7500 cm-1"),
 80: ("K", "C2", "marvel", "pending", "12C2 MARVEL update; SI has 12C-12C_2020update.marvel.inp; MNRAS SI"),
 81: ("K", "CN", "marvel", "pending", "12C14N; full MARVEL input in SI; MNRAS SI"),
 82: ("D:aggregator", "", "", "", "ExoMol 2020 database release"),
 83: ("D:non_marvel_method", "", "", "", "SNAPS precision spectroscopy of H2O"),
 84: ("D:aggregator", "", "", "", "survey of empirical line lists in ExoMol"),
 85: ("D:no_doi_dup", "", "", "", "duplicate of rank 84, no DOI"),
 86: ("K", "CaOH", "marvel", "pending", "MARVEL input+output for CaOH in SI; ApJS SI"),
 87: ("D:no_doi_dup", "", "", "", "duplicate of rank 86, no DOI"),
 88: ("K", "NH", "marvel", "levels+trans", "14NH; SI includes ReadMe.txt describing resistance labels"),
 89: ("K", "O2", "marvel", "pending", "16O2, 7 lowest electronic states; JPCRD (AIP) SI"),
 90: ("D:linelist_only", "", "", "", "SH GYT line list; effective-Hamiltonian fit, no MARVEL set"),
 91: ("K", "MgO", "exomol_linelist", "pending", "LiTY; MARVEL transitions and energy files in SI; MNRAS SI"),
 92: ("K", "H2O", "marvel", "pending", "MARVEL protocol improvements + H216O energies/transitions; RSC PCCP SI"),
 93: ("K", "H2S", "marvel", "levels+trans", "H2 32S, ortho/para split files"),
 94: ("D:pes_linelist", "", "", "", "NH3 PES refinement + near-IR assignments"),
 95: ("D:derived_use", "", "", "", "BeH/BeD/BeT synthetic spectra for JET modelling"),
 96: ("K", "ZrO", "marvel", "pending", "90Zr16O; SI has 90Zr-16O.marvel.inp; ApJ SI"),
 97: ("D:linelist_only", "", "", "", "CH3Cl OYT line list"),
 98: ("D:aggregator", "", "", "", "ExoMol Atlas of opacities"),
 99: ("D:no_doi_dup", "", "", "", "duplicate of rank 98, no DOI"),
 100:("K", "SO2", "marvel", "levels+trans", "S16O2 with 32S/33S/34S/36S"),
 101:("K", "AlH", "exomol_linelist", "pending", "AlHambra 27AlH; MNRAS SI"),
 102:("D:linelist_only", "", "", "", "SH and NS SNaSH line lists"),
 103:("K", "C2H2", "marvel", "levels+trans", "12C2H2, ortho/para MARVEL files"),
 104:("D:measurement_source", "", "", "", "room-temperature deuterated water line lists; a MARVEL source"),
 105:("K", "TiO", "marvel", "pending", "48Ti16O; SI = 48Ti-16O.marvel.inp, 48Ti-16O.energies, 48Ti-16O_FFN_ca33.energies; ApJS SI"),
 106:("D:linelist_only", "", "", "", "H3+ MiZATeP; MARVEL in companion (rank 124)"),
 107:("D:linelist_only", "", "", "", "silane OY2T line list"),
 108:("D:measurement_source", "", "", "", "experimental H2O line list at 1950 K; a MARVEL source"),
 109:("D:no_doi_dup", "", "", "", "duplicate of rank 117, no DOI"),
 110:("K", "NO", "exomol_linelist", "pending", "XABC precursor; MARVEL input file used, SI listing to confirm; MNRAS SI"),
 111:("D:linelist_only", "", "", "", "SiH SiGHTLY line list"),
 112:("D:method_paper", "", "", "", "Small Molecules-Big Data overview"),
 113:("K", "C2", "marvel", "pending", "12C2 experimental levels + partition function; ApJS SI"),
 114:("D:linelist_only", "", "", "", "VO ExoMol XVIII line list"),
 115:("D:linelist_only", "", "", "", "H217O/H218O HotWat78 line lists"),
 116:("D:aggregator", "", "", "", "ExoMol database 2016 release"),
 117:("D:method_paper", "", "", "", "ExoMol software update"),
 118:("D:derived_use", "", "", "", "tunneling analysis of published 14NH3 MARVEL levels"),
 119:("K", "NH3", "marvel", "levels+trans", "14NH3"),
 120:("D:linelist_only", "", "", "", "CS line lists for eight isotopologues"),
 121:("K", "H2O", "iupac", "levels+trans", "IUPAC Part IV: D216O, D217O, D218O"),
 122:("D:aggregator", "", "", "", "IUPAC Technical Report summarising Parts I-IV"),
 123:("D:linelist_only", "", "", "", "HCN/HNC line list"),
 124:("K", "H3+", "marvel", "pending", "rovibrational states of H3+; ACS JCTC SI"),
 125:("K", "H2D+|D2H+", "marvel", "pending", "MARVEL analysis of H2D+ and D2H+; RSC PCCP SI"),
 126:("D:no_doi_dup", "", "", "", "duplicate of rank 129, no DOI"),
 127:("D:method_paper", "", "", "", "MARVEL II algorithmic improvements"),
 128:("D:aggregator", "", "", "", "ExoMol project announcement"),
 129:("K", "H2O", "iupac", "levels+trans", "IUPAC Part III: H216O"),
 130:("D:non_marvel_method", "", "", "", "new inversion method for H217O/H218O level retrieval"),
 131:("D:non_marvel_method", "", "", "", "(000)/(010) levels of HD18O and D218O from nu2 band analysis"),
 132:("K", "CO", "marvel", "levels+trans", "12C16O critical evaluation"),
 133:("K", "H2O", "iupac", "levels+trans", "IUPAC Part II"),
 134:("K", "H2O", "marvel", "levels+trans", "HD18O critical evaluation"),
 135:("K", "H2O", "iupac", "levels+trans", "IUPAC Part I: H217O and H218O"),
 136:("D:no_doi_dup", "", "", "", "duplicate of rank 135, no DOI"),
 137:("D:pes_linelist", "", "", "", "HDO potential energy surface"),

 # --- MEDIUM TIER (138-204) ---
 138:("D:derived_use", "", "", "", "ML isotope-shift extrapolation trained on published MARVEL levels"),
 139:("D:non_marvel_method", "", "", "", "direct-potential-fit of the K2 ground state"),
 140:("D:measurement_source", "", "", "", "sub-Doppler CO2 measurements; levels from effective rovibrational models"),
 141:("D:pes_linelist", "", "", "", "14N216O PES refinement benchmarked against MARVEL/RITZ"),
 142:("D:ab_initio", "", "", "", "CS-He vibrational relaxation rate coefficients"),
 143:("D:measurement_source", "", "", "", "ZrO b3Pi-a3Delta band analysis from Kitt Peak emission spectra"),
 144:("K", "H2O", "marvel", "levels+trans", "H216O reassessment, 6600-7500 cm-1; Elsevier mmc captions invisible - file roles unverified"),
 145:("D:linelist_only", "", "", "", "Ames N2O line lists; empirical positions from IMRHT, not MARVEL"),
 146:("D:derived_use", "", "", "", "NO partition sums from published term values"),
 147:("D:ab_initio", "", "", "", "non-adiabatic corrections to H3+ rovibrational energies"),
 148:("D:ab_initio", "", "", "", "theoretical CO A/B/C/E-X transition study"),
 149:("D:pes_linelist", "", "", "", "OCS potential energy surface"),
 150:("D:measurement_source", "", "", "", "PhD thesis; NICE-OHMS precision measurements of H2O and HD"),
 151:("D:measurement_source", "", "", "", "CLEO conference abstract; 8 um H2CO comb spectroscopy"),
 152:("D:pes_linelist", "", "", "", "N2O PES/DMS + 296 K line lists"),
 153:("D:measurement_source", "", "", "", "HDS hyperfine spectra + global effective-Hamiltonian fit"),
 154:("D:method_paper", "", "", "", "spectroscopic-network heat maps for experiment design"),
 155:("D:pes_linelist", "", "", "", "C2H2 levels from new potential energy surfaces"),
 156:("D:derived_use", "", "", "", "AlH ExoMol line lists applied to Proxima Cen spectra"),
 157:("D:derived_use", "", "", "", "assessment of the published VO line list"),
 158:("D:ab_initio", "", "", "", "ScalIT H3+ eigenstates and quantum labels"),
 159:("D:ab_initio", "", "", "", "RVCI series-expansion convergence study"),
 160:("D:derived_use", "", "", "", "validation tests of the published W2020 levels"),
 161:("D:aggregator", "", "", "", "HITRAN2020 database paper"),
 162:("D:non_marvel_method", "", "", "", "pattern-recognition assignment of methanol OH-stretch overtones"),
 163:("D:ab_initio", "", "", "", "computed CO2 electric quadrupole line list"),
 164:("D:no_doi_dup", "", "", "", "duplicate of rank 163, no DOI"),
 165:("D:measurement_source", "", "", "", "dual-path water-vapour absorption measurements"),
 166:("D:method_paper", "", "", "", "Connecting Spectroscopic Components line-selection method"),
 167:("D:derived_use", "", "", "", "multi-epoch cross-correlation detection of H2O in HD187123b"),
 168:("D:aggregator", "", "", "", "ExoMolOP opacity database"),
 169:("D:preprint_dup", "", "", "", "arXiv preprint of rank 168"),
 170:("D:derived_use", "", "", "", "cross-sections computed from published line lists"),
 171:("D:derived_use", "", "", "", "TiO isotopologue features in stellar spectra"),
 172:("D:derived_use", "", "", "", "TiO opacity in hot-Jupiter thermal inversions"),
 173:("D:linelist_only", "", "", "", "CP line lists; no own empirical set"),
 174:("D:measurement_source", "", "", "", "SI-traceable CO2 transition frequency measurements"),
 175:("D:derived_use", "", "", "", "lidar CH4 retrieval sensitivity to line-list accuracy"),
 176:("D:aggregator", "", "", "", "expert compilation of SO2 absorption lines"),
 177:("D:linelist_only", "", "", "", "jt775 H216O/H218O calculated line lists"),
 178:("D:non_marvel_method", "", "", "", "J-dependent rotational Hamiltonian analysis"),
 179:("D:measurement_source", "", "", "", "sub-Doppler H3+ survey; levels via combination differences + effective Hamiltonian"),
 180:("D:measurement_source", "", "", "", "conference abstract; 1950 K water line list"),
 181:("D:aggregator", "", "", "", "W@DIS information system, deuterated H2S data"),
 182:("D:derived_use", "", "", "", "D2O thermochemical functions from published levels"),
 183:("D:aggregator", "", "", "", "W@DIS information system status report"),
 184:("D:measurement_source", "", "", "", "NH3 Kitt Peak line list; assignments anchored on published MARVEL levels"),
 185:("D:non_marvel_method", "", "", "", "Ritz evaluation of 14N16O X2Pi line positions"),
 186:("D:derived_use", "", "", "", "H216O thermochemical functions from MARVEL+PoKaZaTeL hybrid levels"),
 187:("D:ab_initio", "", "", "", "NH3 levels from an ab initio potential energy surface"),
 188:("D:linelist_only", "", "", "", "UCL-296 CO2 line list with ab initio intensities"),
 189:("D:measurement_source", "", "", "", "CRDS of 17O-enriched water; levels from own measurements"),
 190:("D:method_paper", "", "", "", "spectroscopic networks as complex systems"),
 191:("D:ab_initio", "", "", "", "QED correction to H3+ energies"),
 192:("D:measurement_source", "", "", "", "hot HD17O emission spectra; (000)/(010) rotational levels"),
 193:("D:non_marvel_method", "", "", "", "empirical water line list built from non-MARVEL level retrieval"),
 194:("D:aggregator", "", "", "", "CDSD-296 databank"),
 195:("D:measurement_source", "", "", "", "new HD18O/D218O assignments from an enriched water spectrum"),
 196:("D:pes_linelist", "", "", "", "Ames-1 CO2 PES + 12C16O2 line list"),
 197:("D:linelist_only", "", "", "", "jt522 H218O/H217O line lists"),
 198:("D:pes_linelist", "", "", "", "global water PES/DMS and computed spectrum"),
 199:("D:method_paper", "", "", "", "rigid-rotor decomposition and axis embedding"),
 200:("D:method_paper", "", "", "", "review: the fourth age of quantum chemistry"),
 201:("D:method_paper", "", "", "", "review: variational line-list calculations"),
 202:("D:ab_initio", "", "", "", "finite-basis vibrational energy levels"),
 203:("D:ab_initio", "", "", "", "ab initio water dipole moment surface"),
 204:("D:pes_linelist", "", "", "", "water line lists from a spectroscopically determined PES"),

# --- LOW TIER (205-309), shallow title/abstract pass -------------------------
# New reason this tier: off_topic = the citation is noise; the paper is not
# about molecular spectroscopy at all.
# Ranks 227, 233, 242, 264, 294 are deliberately absent - Csaszar-group titles
# that may hide a network inversion; no OA PDF reachable, needs a browser pass.
 205:("D:measurement_source", "", "", "", "FeH laser spectroscopy; new I4Phi state from own LIF measurements"),
 206:("D:measurement_source", "", "", "", "H2O difference-frequency THz; beyond-Voigt line profiles"),
 207:("D:measurement_source", "", "", "", "SO2 FT spectrum 4700-5200; effective-Hamiltonian analysis of own spectra"),
 208:("D:ab_initio", "", "", "", "exact factorization method for bound vibrational states"),
 209:("D:derived_use", "", "", "", "HITRAN2024 partition sums"),
 210:("D:pes_linelist", "", "", "", "jt949 14N2-16O PES/DMS + variational spectra"),
 211:("D:derived_use", "", "", "", "H3+ emission limits for WASP-80b/69b; uses published line lists"),
 212:("D:measurement_source", "", "", "", "H2-12CO 4450-5000; modeling of own high-resolution spectra"),
 213:("D:aggregator", "", "", "", "ReSpecTh kinetics/spectroscopy/thermochemistry datasets"),
 214:("D:method_paper", "", "", "", "review: joint use of experimental, empirical and computed data"),
 215:("D:ab_initio", "", "", "", "uracil IR line shapes from VPT2 and hybrid QM"),
 216:("D:method_paper", "", "", "", "review: data challenges for exoplanet high-resolution spectroscopy"),
 217:("D:method_paper", "", "", "", "Ariel data availability and requirements white paper"),
 218:("D:method_paper", "", "", "", "review: cavity-enhanced precision molecular spectroscopy"),
 219:("D:off_topic", "", "", "", "energy harvesting technologies; citation noise"),
 220:("D:ab_initio", "", "", "", "ab initio centrifugal distortion constants, A-reduced Hamiltonians"),
 221:("D:preprint_dup", "", "", "", "SSRN preprint of rank 210"),
 222:("D:measurement_source", "", "", "", "H2-12CO 3700-4450; new quantum assignments from own spectra"),
 223:("D:preprint_dup", "", "", "", "SSRN preprint of rank 222"),
 224:("D:method_paper", "", "", "", "short guide to laser-based gas-phase spectroscopy"),
 225:("D:method_paper", "", "", "", "verification labels for rovibronic energy uncertainties; SN tool"),
 226:("D:method_paper", "", "", "", "Hungarian version of the fourth-age-of-quantum-chemistry review"),
 228:("D:ab_initio", "", "", "", "aminoacetonitrile structure and IR spectrum"),
 229:("D:ab_initio", "", "", "", "F12 double-hybrid DFT harmonic frequencies"),
 230:("D:ab_initio", "", "", "", "diazophosphane spectroscopic characterization"),
 231:("D:ab_initio", "", "", "", "propynal IR, spectroscopic constants and hot bands"),
 232:("D:off_topic", "", "", "", "fuzzy comprehensive evaluation of gas absorption spectra"),
 233:("K", "H2O", "marvel", "pending", "H2-16O (200) parent; 71 new NICE-OHMS lines + literature transitions inverted on the SN; relative energies for 59 states up to J=6"),
 234:("D:measurement_source", "", "", "", "FT spectroscopy of water vapour, 0.9 um window"),
 235:("D:measurement_source", "", "", "", "buffer-gas-cooled CaOH low-J A-X transitions"),
 236:("D:method_paper", "", "", "", "review: high-accuracy line lists for hot atmospheres"),
 237:("D:non_marvel_method", "", "", "", "CN X~A~B coupled-channel deperturbation of literature data"),
 238:("D:measurement_source", "", "", "", "far-IR water vapour 50-720; database validation, Part 1"),
 239:("D:aggregator", "", "", "", "VIBFREQ1295 vibrational frequency database"),
 240:("D:method_paper", "", "", "", "Nature Rev primer: computational molecular spectroscopy"),
 241:("D:method_paper", "", "", "", "jt833 quantum labels from angular-momentum projections"),
 242:("K", "H2O", "marvel", "pending", "H2-18O; 195 NICE-OHMS + 6 microwave lines, SNAPS-selected; all pure rotational energies up to J=8"),
 243:("D:method_paper", "", "", "", "review: molecular diatomic spectroscopy data"),
 244:("D:ab_initio", "", "", "", "PN A1Pi-X1Sigma+ transition properties"),
 245:("D:off_topic", "", "", "", "gas transmittance dependence on detector size"),
 246:("D:ab_initio", "", "", "", "PN rovibronic spectroscopy from first principles"),
 247:("D:ab_initio", "", "", "", "CN non-adiabatic couplings among low-lying doublets"),
 248:("D:method_paper", "", "", "", "autoECART energy-conservation analysis tool"),
 249:("D:off_topic", "", "", "", "femtochemistry of H + HOD exchange reactions"),
 250:("D:linelist_only", "", "", "", "14NH3 line list for the 2.3 um region"),
 251:("D:measurement_source", "", "", "", "CH3OH/CD3OH synchrotron near-free-rotor FIR spectra"),
 252:("D:measurement_source", "", "", "", "water 5690-8340 empirical line centres from own spectra"),
 253:("D:derived_use", "", "", "", "water vapour detection in Earth analogs; reflected-light retrieval"),
 254:("D:off_topic", "", "", "", "the gamma function in quantum theory"),
 255:("D:derived_use", "", "", "", "H2O-N2 line-shape parameters and their prediction"),
 256:("D:aggregator", "", "", "", "MoLLIST line list collection"),
 257:("D:method_paper", "", "", "", "essay: digitalis kemia"),
 258:("D:aggregator", "", "", "", "HITEMP NO/NO2/N2O line parameters"),
 259:("D:derived_use", "", "", "", "TDLAS in situ combustion diagnostics"),
 260:("D:non_marvel_method", "", "", "", "14N2-16O non-polyad effective-Hamiltonian global modeling"),
 261:("D:method_paper", "", "", "", "PhD thesis: theory of spectroscopic networks"),
 262:("D:pes_linelist", "", "", "", "Ames SO2 IR intensity validation and new line lists"),
 263:("D:measurement_source", "", "", "", "Lamb-dip CRDS of H2-16O near 1.4 um"),
 265:("D:measurement_source", "", "", "", "ammonia absorption spectra near 1 um"),
 266:("D:non_marvel_method", "", "", "", "CH5+ from lines to states without a model; pattern recognition"),
 267:("D:measurement_source", "", "", "", "1943 K H2-16O emission spectrum, 6600-7050"),
 268:("D:measurement_source", "", "", "", "HDO LED-based FTS, 11200-12400"),
 269:("D:method_paper", "", "", "", "review: hot-molecule laboratory data needs"),
 270:("D:ab_initio", "", "", "", "jt706 high-accuracy H3+ rovibrational calculations"),
 271:("D:method_paper", "", "", "", "cycle bases for spectroscopic networks"),
 272:("D:measurement_source", "", "", "", "NH3 high-temperature absorption, 2100-5500"),
 273:("D:measurement_source", "", "", "", "water vapour 2.2 um window; measurements and database"),
 274:("D:aggregator", "", "", "", "Landolt-Bornstein intro, non-linear triatomic parameters"),
 275:("D:aggregator", "", "", "", "GEISA 2015 edition"),
 276:("D:measurement_source", "", "", "", "water vapour spectroscopic database 5850-8340"),
 277:("D:aggregator", "", "", "", "TheoReTS information system"),
 278:("D:method_paper", "", "", "", "on spectra of spectra; network mathematics"),
 279:("D:measurement_source", "", "", "", "NH3 high-temperature absorption, 500-2100"),
 280:("D:measurement_source", "", "", "", "water vapour 1.25 um window, 7911-8337"),
 281:("D:ab_initio", "", "", "", "zero-cost estimation of zero-point energies"),
 282:("D:off_topic", "", "", "", "vascular oscillogram analysis; citation noise"),
 283:("D:aggregator", "", "", "", "Landolt-Bornstein non-linear triatomic molecules, introduction"),
 284:("D:linelist_only", "", "", "", "HD16O line list for terrestrial-planet atmospheres"),
 285:("D:measurement_source", "", "", "", "CW-CRDS of deuterated water, 1.58 um window"),
 286:("D:aggregator", "", "", "", "Landolt-Bornstein table: H2-17O calculated band origins"),
 287:("D:aggregator", "", "", "", "Landolt-Bornstein table: H2-18O calculated band origins"),
 288:("D:measurement_source", "", "", "", "CRDS of 18O-enriched CO2 5850-7000, Part III"),
 289:("D:off_topic", "", "", "", "external-cavity diode pump for difference-frequency generation"),
 290:("D:aggregator", "", "", "", "HITRAN2012 database"),
 291:("D:measurement_source", "", "", "", "comb-linked CRDS; kHz-level transition frequencies"),
 292:("D:method_paper", "", "", "", "spectroscopic networks (11CsFuxx)"),
 293:("D:method_paper", "", "", "", "role of intensities in spectroscopic-network characteristics"),
 294:("K", "H2CCO", "marvel", "pending", "ketene; 3194 validated transitions from 12 refs form ortho+para SNs; 1251+471 inverted energy levels; AIP SI not yet listed"),
 295:("D:measurement_source", "", "", "", "ICLAS of H2-18O, 13540-14100"),
 296:("D:measurement_source", "", "", "", "water 1.25 um transparency window, 7408-7920"),
 297:("D:non_marvel_method", "", "", "", "14N2-16O polyad effective-Hamiltonian global modeling"),
 298:("D:method_paper", "", "", "", "error propagation of model parameters"),
 299:("D:measurement_source", "", "", "", "high-temperature ammonia spectra, 780-2100"),
 300:("D:method_paper", "", "", "", "NEAT: network of computed reaction enthalpies; thermochemistry"),
 301:("D:method_paper", "", "", "", "quantum labels for variationally computed eigenstates (NMD/RRD)"),
 302:("D:aggregator", "", "", "", "W@DIS ontology for water spectroscopy information resources"),
 303:("D:non_marvel_method", "", "", "", "14N15N16O/15N14N16O effective-Hamiltonian global fits"),
 304:("D:aggregator", "", "", "", "W@DIS computed knowledge base of water spectroscopy resources"),
 305:("D:aggregator", "", "", "", "news item on the IUPAC water transition database"),
 306:("D:measurement_source", "", "", "", "CW-CRDS of 18O-enriched water near 1.6 um"),
 307:("D:method_paper", "", "", "", "active database approach chapter (07CsCzFu)"),
 308:("D:method_paper", "", "", "", "toward first-principles complete spectroscopy of small molecules"),
 309:("D:derived_use", "", "", "", "water lines as far-IR frequency standards, 15-170"),
}

# Links found outside the Elsevier asset probe. rank -> [(url, link_kind), ...]
EXTRA_LINKS = {
 9:  [("https://osf.io/9pzew", "repository")],
 26: [("https://osf.io/4e237", "repository")],
}
